// Type declarations for the real wasm-pack output at
// core/bindings/wasm/pkg/index.js (generated by `npm run prepare-wasm`).
// Production components import directly from that module — never from a
// hand-written JS stub — so these declarations must cover the full API
// surface used by the web client.  See core/bindings/wasm/src/lib.rs for
// the authoritative Rust definitions.
declare module '../../../core/bindings/wasm/pkg/index.js' {
  export class IdentityHandle {
    public_bytes(): Uint8Array;
  }
  export class GroupHandle {}

  export function generate_identity(): IdentityHandle;
  export function group_create(selfIdentity: IdentityHandle): GroupHandle;
  export function group_add_member(group: GroupHandle, publicBytes: Uint8Array): GroupHandle;
  export function group_remove_member(group: GroupHandle, publicBytes: Uint8Array): GroupHandle;
  export function group_encrypt(
    group: GroupHandle,
    senderIdentity: IdentityHandle,
    plaintextBytes: Uint8Array,
  ): Uint8Array;
  export function group_decrypt(
    group: GroupHandle,
    memberIdentity: IdentityHandle,
    ciphertext: Uint8Array,
  ): Uint8Array;
  export function derive_safety_number(
    localIdentityKey: Uint8Array,
    remoteIdentityKey: Uint8Array,
  ): string;
}
