// Type declarations for the wasm-pack output at
// core/bindings/wasm/pkg/index.js (generated by `npm run prepare-wasm`).
//
// The pkg/ directory is gitignored, so these committed declarations are
// resolved via the tsconfig.json `paths` mapping to let `tsc --noEmit`
// type-check on a fresh checkout that has not yet built the WASM.
// See core/bindings/wasm/src/lib.rs for the authoritative Rust definitions.

export class IdentityHandle {
  public_bytes(): Uint8Array;
}

export class GroupHandle {}

export function generate_identity(): IdentityHandle;
export function group_create(selfIdentity: IdentityHandle): GroupHandle;
export function group_add_member(group: GroupHandle, publicBytes: Uint8Array): GroupHandle;
export function group_remove_member(group: GroupHandle, publicBytes: Uint8Array): GroupHandle;
export function group_encrypt(
  group: GroupHandle,
  senderIdentity: IdentityHandle,
  plaintextBytes: Uint8Array,
): Uint8Array;
export function group_decrypt(
  group: GroupHandle,
  memberIdentity: IdentityHandle,
  ciphertext: Uint8Array,
): Uint8Array;
export function derive_safety_number(
  localIdentityKey: Uint8Array,
  remoteIdentityKey: Uint8Array,
): string;